### ISSUE TITLE
NFR(Non Funtional Requirements)를 구현하다

### ISSUE THREAD

**Issue by chaeeerish** [goormthon-Univ/2024_BEOTKKOTTHON_TEAM_27_BE_1#15]
## Description 🖊️
- 필수 API 구현이 끝난 이후, NFR(Non Funtional Requirements)를 구현하다

## To-do 🧑‍💻
- [ ] @Synchronized
- [ ] @Http CODE
- [ ] Convention 통일
- [ ] JpaAuditingConfiguration.java 삭제
- [ ] dto 밖으로 빼기
- [ ] builder + createDomain => 생성자
- [ ] Spring Security 적용
- [ ] 에러 처리
