### ISSUE TITLE
코드 리팩토링을 진행한다

### ISSUE THREAD

**Issue by chaeeerish** [goormthon-Univ/2024_BEOTKKOTTHON_TEAM_27_BE_1#3]
## Description 🖊️
- 코드 리팩토링을 진행한다

## To-do 🧑‍💻
- [ ] 메모리 -> JPA 변경
- [ ] 불필요한 코드를 제거한다
- [ ] 불필요한 import를 제거한다
- [ ] 불필요한 메소드를 제거한다
- [ ] 코드 정렬을 맞춘다
